SUMMARY = "DrumGizmo is drum plugin and stand-alone application"
HOMEPAGE = "https://www.drumgizmo.org"
LICENSE = "LGPLv3"
LIC_FILES_CHKSUM = "file://COPYING;md5=e6a600fd5e1d9cbde2d983680233ad02"

SRC_URI = "http://www.drumgizmo.org/releases/${BPN}-${PV}/${BPN}-${PV}.tar.gz"
SRC_URI[md5sum] = "fb2340ab61062e0814f4539657dc14ec"
SRC_URI[sha256sum] = "67a2d9d4aa11ee92f000cc8a49710408c2328b2581a5339be3cbfe91d99feb2e"
PV = "0.9.18.1"
