SUMMARY = "DrumGizmo is drum plugin and stand-alone application"
HOMEPAGE = "https://www.drumgizmo.org"
LICENSE = "LGPLv3"
LIC_FILES_CHKSUM = "file://COPYING;md5=e6a600fd5e1d9cbde2d983680233ad02"

SRC_URI = "http://www.drumgizmo.org/releases/${BPN}-${PV}/${BPN}-${PV}.tar.gz"
SRC_URI[md5sum] = "370b0931f5ab95952d0b85eea2533837"
SRC_URI[sha256sum] = "a1a31b2af5544e39e8e19c370fa6fee0a372a14fffa762d4d12debf4e711ec9c"
PV = "0.9.17"
